#+TITLE: SMWeather: simple weather forcasts via Text
#+STARTUP: content
* Intro
  SMWeather provides a simple service: text a number anytime you want and get the weather
  forecast for the next 24 hours. Your account can be managed online, where you can change
  your location. This service is free for now...

* Feature (*one, uno, 1, singular*)
  * Text the SMWeather number any time of day and receive a text message with the forecast for the next 24 hours.
  * Keep any other feature ideas to yourself, actually don't even think about them, this is the only feature. until it is complete.
* TO IMPLEMENT:
  * I see this app as having 2 main portions, with a possible third
** Web UI
*** Welcome page
    * Replace the default welcome page
    * should have a brief description and a
*** User Account creation
*** User Account settings
** Data Processing
*** Deals with Twilio, to send/receive texts
*** Deals with a weather service, to fetch forecasts
**** Forecast.io?
     * they have a pretty good free tier service, first 1000 api calls free every day.
** Data Storage(?)
*** Stores user info,
    * may need to store phone number and associated location for forecasts.
*** Used by both of the other 2 parts
